### ISSUE TITLE
Errors

### ISSUE THREAD

**Issue by Ory4n** [bradtraversy/devconnector#1]
Hi can you help with these issues please, I am new to react

C:\Users\infoo\Documents\GitHub\devconnector>npm run dev

> devconnector@1.0.0 dev C:\Users\infoo\Documents\GitHub\devconnector
> concurrently "npm run server" "npm run client"

[1]
[1] > devconnector@1.0.0 client C:\Users\infoo\Documents\GitHub\devconnector
[1] > npm start --prefix client
[1]
[0]
[0] > devconnector@1.0.0 server C:\Users\infoo\Documents\GitHub\devconnector
[0] > nodemon server.js
[0]
[0] [nodemon] 1.17.4
[0] [nodemon] to restart at any time, enter `rs`
[0] [nodemon] watching: *.*
[0] [nodemon] starting `node server.js`
[1]
[1] > client@0.1.0 start C:\Users\infoo\Documents\GitHub\devconnector\client
[1] > react-scripts start
[1]
[1] 'react-scripts' is not recognized as an internal or external command,
[1] operable program or batch file.
[1] npm ERR! code ELIFECYCLE
[1] npm ERR! errno 1
[1] npm ERR! client@0.1.0 start: `react-scripts start`
npm ERR! Exit status 1
[1] npm ERR!
[1] npm ERR! Failed at the client@0.1.0 start script.
[1] npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
[1]
[1] npm ERR! A complete log of this run can be found in:
[1] npm ERR!     C:\Users\infoo\AppData\Roaming\npm-cache\_logs\2018-05-22T09_50_19_900Z-debug.log
[1] npm ERR! code ELIFECYCLE
[1] npm ERR! errno 1
[1] npm ERR! devconnector@1.0.0 client: `npm start --prefix client`
[1] npm ERR! Exit status 1
[1] npm ERR!
[1] npm ERR! Failed at the devconnector@1.0.0 client script.
[1] npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
[1]
[1] npm ERR! A complete log of this run can be found in:
[1] npm ERR!     C:\Users\infoo\AppData\Roaming\npm-cache\_logs\2018-05-22T09_50_19_948Z-debug.log
[1] npm run client exited with code 1
[0] module.js:545
[0]     throw err;
[0]     ^
[0]
[0] Error: Cannot find module './keys_dev'
[0]     at Function.Module._resolveFilename (module.js:543:15)
[0]     at Function.Module._load (module.js:470:25)
[0]     at Module.require (module.js:593:17)
[0]     at require (internal/module.js:11:18)
[0]     at Object.<anonymous> (C:\Users\infoo\Documents\GitHub\devconnector\config\keys.js:4:20)
[0]     at Module._compile (module.js:649:30)
[0]     at Object.Module._extensions..js (module.js:660:10)
[0]     at Module.load (module.js:561:32)
[0]     at tryModuleLoad (module.js:501:12)
[0]     at Function.Module._load (module.js:493:3)
[0]     at Module.require (module.js:593:17)
[0]     at require (internal/module.js:11:18)
[0]     at Object.<anonymous> (C:\Users\infoo\Documents\GitHub\devconnector\routes\api\users.js:6:14)
[0]     at Module._compile (module.js:649:30)
[0]     at Object.Module._extensions..js (module.js:660:10)
[0]     at Module.load (module.js:561:32)
[0] [nodemon] app crashed - waiting for file changes before starting...

**Comment by SamDHarris** [comment]
Hi @Ory4n I encountered the same issue. For some reason, it cannot find the react-scripts module. The best way to go about resolving this is by reinstalling react-scripts by doing `npm i -S react-scripts`.

Hope that helps :)

**Comment by Ory4n** [comment]
Thank you that seemed to have done the trick. Really appreciate the assistance. 

I have new error now 🗡 

 module.js:545
[0]     throw err;
[0]     ^
[0]
[0] Error: Cannot find module './keys_dev'
[0]     at Function.Module._resolveFilename (module.js:543:15)
[0]     at Function.Module._load (module.js:470:25)
[0]     at Module.require (module.js:593:17)
[0]     at require (internal/module.js:11:18)
[0]     at Object.<anonymous> (C:\Users\infoo\Documents\GitHub\devconnector\config\keys.js:4:20)
[0]     at Module._compile (module.js:649:30)
[0]     at Object.Module._extensions..js (module.js:660:10)
[0]     at Module.load (module.js:561:32)
[0]     at tryModuleLoad (module.js:501:12)
[0]     at Function.Module._load (module.js:493:3)
[0]     at Module.require (module.js:593:17)
[0]     at require (internal/module.js:11:18)
[0]     at Object.<anonymous> (C:\Users\infoo\Documents\GitHub\devconnector\routes\api\users.js:6:14)
[0]     at Module._compile (module.js:649:30)
[0]     at Object.Module._extensions..js (module.js:660:10)
[0]     at Module.load (module.js:561:32)
[0] [nodemon] app crashed - waiting for file changes before starting...
[1] Starting the development server...
[1]
[1] Failed to compile.
[1]
[1] ./src/actions/postActions.js
[1] Module not found: Can't resolve 'axios' in 'C:\Users\infoo\Documents\GitHub\devconnector\client\src\actions'

**Comment by SamDHarris** [comment]
@Ory4n it appears that node cannot find the keys_dev file in the current directory. Are you sure that it is in the current directory?
