### ISSUE TITLE
Sign up issue

### ISSUE THREAD

**Issue by SiddharthVarshney** [bradtraversy/devconnector#44]
Submit button at sign up is not working.
Getting error in terminal saying 
`Error: Username containing an unescaped at-sign
[0]     at parseConnectionString (/home/siddharth/Documents/devconnector/node_modules/mongodb/lib/url_parser.js:186:13)
[0]     at parseHandler (/home/siddharth/Documents/devconnector/node_modules/mongodb/lib/url_parser.js:129:14)
[0]     at module.exports (/home/siddharth/Documents/devconnector/node_modules/mongodb/lib/url_parser.js:25:12)
[0]     at deprecated (internal/util.js:73:15)
[0]     at connect (/home/siddharth/Documents/devconnector/node_modules/mongodb/lib/operations/mongo_client_ops.js:180:3)
[0]     at connectOp (/home/siddharth/Documents/devconnector/node_modules/mongodb/lib/operations/mongo_client_ops.js:284:3)
[0]     at executeOperation (/home/siddharth/Documents/devconnector/node_modules/mongodb/lib/utils.js:420:24)
[0]     at MongoClient.connect (/home/siddharth/Documents/devconnector/node_modules/mongodb/lib/mongo_client.js:168:10)
[0]     at Promise (/home/siddharth/Documents/devconnector/node_modules/mongoose/lib/connection.js:521:12)
[0]     at new Promise (<anonymous>)
[0]     at NativeConnection.Connection.openUri (/home/siddharth/Documents/devconnector/node_modules/mongoose/lib/connection.js:518:19)
[0]     at Mongoose.connect (/home/siddharth/Documents/devconnector/node_modules/mongoose/lib/index.js:270:15)
[0]     at Object.<anonymous> (/home/siddharth/Documents/devconnector/server.js:22:4)
[0]     at Module._compile (internal/modules/cjs/loader.js:723:30)
[0]     at Object.Module._extensions..js (internal/modules/cjs/loader.js:734:10)
[0]     at Module.load (internal/modules/cjs/loader.js:620:32)`

**Comment by rimoslav** [comment]
Hope this can help: [https://github.com/mrvautin/adminMongo/issues/147](url)
