### ISSUE TITLE
Cannot find module '../../models/User'

### ISSUE THREAD

**Issue by mikechavez** [bradtraversy/devconnector#51]
You can see my repo [here](https://github.com/mikechavez/devconnector)
I can't seem to figure out this bug. I run the code on my local machine and it works perfectly, but once deployed to Heroku, I get this error in the logs:

2019-02-06T04:57:15.843298+00:00 app[web.1]: Error: Cannot find module '../../models/User'
2019-02-06T04:57:15.843300+00:00 app[web.1]: at Function.Module._resolveFilename (internal/modules/cjs/loader.js:581:15)
2019-02-06T04:57:15.843301+00:00 app[web.1]: at Function.Module._load (internal/modules/cjs/loader.js:507:25)
2019-02-06T04:57:15.843303+00:00 app[web.1]: at Module.require (internal/modules/cjs/loader.js:637:17)
2019-02-06T04:57:15.843304+00:00 app[web.1]: at require (internal/modules/cjs/helpers.js:22:18)
2019-02-06T04:57:15.843305+00:00 app[web.1]: at Object.<anonymous> (/app/routes/api/users.js:14:14)
2019-02-06T04:57:15.843306+00:00 app[web.1]: at Module._compile (internal/modules/cjs/loader.js:689:30)
2019-02-06T04:57:15.843307+00:00 app[web.1]: at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
2019-02-06T04:57:15.843309+00:00 app[web.1]: at Module.load (internal/modules/cjs/loader.js:599:32)
2019-02-06T04:57:15.843310+00:00 app[web.1]: at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
2019-02-06T04:57:15.843311+00:00 app[web.1]: at Function.Module._load (internal/modules/cjs/loader.js:530:3)
2019-02-06T04:57:15.843312+00:00 app[web.1]: at Module.require (internal/modules/cjs/loader.js:637:17)
2019-02-06T04:57:15.843313+00:00 app[web.1]: at require (internal/modules/cjs/helpers.js:22:18)
2019-02-06T04:57:15.843314+00:00 app[web.1]: at Object.<anonymous> (/app/server.js:7:15)
2019-02-06T04:57:15.843315+00:00 app[web.1]: at Module._compile (internal/modules/cjs/loader.js:689:30)
2019-02-06T04:57:15.843317+00:00 app[web.1]: at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
2019-02-06T04:57:15.843318+00:00 app[web.1]: at Module.load (internal/modules/cjs/loader.js:599:32)
2019-02-06T04:57:15.850831+00:00 app[web.1]: npm ERR! code ELIFECYCLE
2019-02-06T04:57:15.851207+00:00 app[web.1]: npm ERR! errno 1
2019-02-06T04:57:15.852219+00:00 app[web.1]: npm ERR! devconnector@1.0.0 start: `node server.js`
2019-02-06T04:57:15.852339+00:00 app[web.1]: npm ERR! Exit status 1
2019-02-06T04:57:15.852535+00:00 app[web.1]: npm ERR!
2019-02-06T04:57:15.852647+00:00 app[web.1]: npm ERR! Failed at the devconnector@1.0.0 start script.
2019-02-06T04:57:15.852789+00:00 app[web.1]: npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
2019-02-06T04:57:15.859626+00:00 app[web.1]:
2019-02-06T04:57:15.859796+00:00 app[web.1]: npm ERR! A complete log of this run can be found in:
2019-02-06T04:57:15.859885+00:00 app[web.1]: npm ERR!     /app/.npm/_logs/2019-02-06T04_57_15_854Z-debug.log
2019-02-06T04:57:15.935046+00:00 heroku[web.1]: State changed from starting to crashed
2019-02-06T04:57:15.920284+00:00 heroku[web.1]: Process exited with status 1

**Comment by mikechavez** [comment]
I was able to solve this issue. My _Users.js_ file was being tracked by git as _users.js_. Once I changed the filename to be capitalized in git and pushed this change to Heroku, everything worked.
